* Steps to upgrade 1a distro switches
- Begin on Friday at Midnight
- Run diagnostics
- Contingency: revert back to using core01 and core02 after an undecided period of time.
** Turn off null route
** Remove default route
** Remove Vlans from trunk
** Shutdown link to core01
** Shutdown link to core02
** Turn on null route
* Dark Fiber Ring
- Purpose: to upgrade to a 10 GB link to sell additional bandwidth to ASO
- Timeline: Mid Jan
- Provider: Lightower
** QFX Switch
** Upgrade order
- Nov - Dec
- Remove Vlans off of the trunk
- MUX MEL <-> OTR
- Upgrade to QFX and map a psudo layer 2 VPN
** Edge to Chicago
- Pick up multiple carriers to SJC
** Edge to Miami 
* Libre NMS
- Login: https://nms.nexcess.net
- PHP/MySQL application which collects data using SNMP.
- Makes use of RRDTool Package.
- Installation Guide for RHEL/CentOS: http://docs.librenms.org/Installation/Installing-LibreNMS/
- IP: 208.69.120.12
- Server Name: netmon02.nexcess.net
- Hostname: nms.nexcess.net
- Set Polling Options: https://nms.nexcess.net/settings/sub=external/
- Oxidzed: Polls device config, version management.
** DEV-Env 
http://nms-dev.nexcess.net/
jcrist-dev
WetMeceak2
** Python JUNOS
https://github.com/job/py-junos-eznc
** RRDTool (Round Robin Database Tool)
Purpose: Logs and analyzes gathered data
*** Documentation
/usr/share/doc/rrdtool-1.4.7/README
file:///usr/share/doc/rrdtool/html/index.html
*** Examples
/usr/share/rrdtool/examples
/usr/share/doc/rrdtool-1.4.7/examples
*** Mailing Lists
rrd-announce    LOW volume RRDtool Announcements List (Only Stable Releases)
rrd-users       For discussion amongst people who use RRDtool in their applications
rrd-developers  For people who actually HACK RRDtool code

To subscribe to <MAILGLIST> send a message with the subject 'subscribe'
to <MAILGLIST>-request@lists.oetiker.ch

Note, that postings to rrd-announce will always be cross-posted 
to rrd-users and rrd-developers as well.


*** Issues
**** The following file systems are full
vpn-01.oys-01.lhr.nexcess.net	/dev/md1, mounted on: /junos		407MB / 407MB0B	100%
vpn-01.spt-01.bne.nexcess.net	/dev/md1, mounted on: /junos		411MB / 411MB0B	100%
fw1b01-01.mel.dtw.nexcess.net	/dev/md1, mounted on: /junos		740MB / 740MB0B	100%
vpn-01.mel-01.dtw.nexcess.net	/dev/md1, mounted on: /junos		792MB / 792MB0B	100%
vpn-01.mel-01.dtw.nexcess.net	/cf, mounted on: /junos/cf		19.5MB / 19.5MB28kB	100%
fw1a01-01.mel.dtw.nexcess.net	/dev/md1, mounted on: /junos		737MB / 737MB0B	100%
vpn-01.nts-01.mia.nexcess.net	/dev/md1, mounted on: /junos		406MB / 406MB0B	100%
vpn-01.jwl-01.ams.nexcess.net	/dev/md1, mounted on: /junos		409MB / 409MB0B	100%
vpn-01.mcb-01.sjc.nexcess.net	/dev/md1, mounted on: /junos		406MB / 406MB0B	100%
vpn-01.bou-01.syd.nexcess.net	/dev/md1, mounted on: /junos		409MB / 409MB0B	100%
client-vpn-01.kel-01.lgw.nexcess.net	/dev/md1, mounted on: /junos		411MB / 411MB0B	100%
vpn-01.kel-01.lgw.nexcess.net	/dev/md1, mounted on: /junos		792MB / 792MB0B	100%
* WAN Guard
https://netconsole-45053.nexcess.net/wanguard/index.php
* Future Hosting
https://internal.fhinternal.com/login
* Arbor SP
- Arbor Peakflow
https://asp01.mel.dtw.nexcess.net/
* MEL SSL VPN Admin
- Admin panel for MEL VPN
https://172.16.0.3/dana-admin/
* 4D Data Centers
- Ticketing system for LHR
https://portal.4d-dc.com/
